clone:
  recursive: true
  submodule_override:
    source/themes/cocoa-hugo-theme: https://github.com/fuegowolf/cocoa-hugo-theme.git

build:
  image: ubuntu:latest
  commands:
    - apt-get update && apt-get install -y hugo
    - hugo --source="source" --buildDrafts

publish:
  docker:
    registry: creus.fuegowolf.me:5000
    username: fuego
    password: $$PASSWORD
    email: alexistacnet@gmail.com
    repo: kodewolf/kodewolf
    tag: $$BRANCH
    file: Dockerfile
    insecure: false
    when:
      branch: [master, develop]

deploy:
  sftp:
    host: fuegowolf.me
    username: fuego
    password: $$PASSWORD
    destination_path: /home/fuego/Projets/kodewolf/
    files:
      - cronos.conf
      - cronos-special.conf
      - docker-compose.cronos.yml
    when:
      branch: [master, develop]
  ssh:
    host: fuegowolf.me
    user: fuego
    commands:
      - cd ~/Projets/kodewolf
      - docker pull creus.fuegowolf.me:5000/kodewolf/kodewolf:$$BRANCH
      - docker-compose -f docker-compose.cronos.yml up -d
      - cp cronos.conf ~/Projets/frostfire/cronos/projects/kodewolf.conf
      - cp cronos-special.conf ~/Projets/frostfire/global-nginx/specials/kodewolf.conf
      - cd ~/Projets/frostfire
      - docker-compose -f docker-compose.admin.yaml run --rm letsencrypt generate.sh kodewolf.com
      - docker-compose up -d --build global-nginx cronos-nginx
    when:
      branch: [master, develop]

notify:
  webhook:
    urls:
      - https://cronos.fuegowolf.me/amiral/send_message