sudo: required

language: go

services:
  - docker

install: go get -v github.com/spf13/hugo

script:
  - hugo --source="source" --buildDrafts
  - docker build -t cronos.fuegowolf.me:5000/kodewolf/kodewolf:$TRAVIS_BRANCH .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" cronos.fuegowolf.me:5000
  - docker push cronos.fuegowolf.me:5000/kodewolf/kodewolf:$TRAVIS_BRANCH