version: '2'
 
services:
  kodewolf:
    image: creus.codewolf.fr:5000/kodewolf/kodewolf:master
    networks:
      - cronos
    restart: always

networks:
  cronos:
    external: 
      name: frostfire_cronos