version: '2'
 
services:
  codewolf:
    image: creus.codewolf.fr:5000/codewolf/codewolf:master
    networks:
      - cronos
    restart: always

networks:
  cronos:
    external: 
      name: frostfire_cronos