baseurl = "https://codewolf.fr/"
theme = "cocoa-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Alexis Tacnet"
title = "Codewolf"
pygmentsuseclasses = true
disqusshortname = "codewolf"
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
author = "Alexis Tacnet"
cachebuster = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "I'm a man who loves to do code ! I'm very interested in Machine Learning and I would like to share my experiences about this exciting subject."
faviconfile = "images/logo.png"
highlightjs = true
lang = "en"
github = "https://github.com/fuegowolf"
email = "alexistacnet@gmail.com"
linkedin = "https://www.linkedin.com/in/alexis-tacnet-aa0478109?trk=hp-identity-name"
twitter = "https://twitter.com/Cruator"