baseurl = "https://kodewolf.com/"
theme = "cocoa-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Alexis Tacnet"
title = "Kodewolf"
pygmentsuseclasses = true
disqusshortname = "kodewolf"
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
author = "Alexis Tacnet"
cachebuster = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "A simple blog about my coder's life : coding, devops things and machine learning."
faviconfile = "images/logo.png"
highlightjs = true
lang = "en"
github = "https://github.com/fuegowolf"
email = "alexistacnet@gmail.com"
linkedin = "https://www.linkedin.com/in/alexis-tacnet-aa0478109?trk=hp-identity-name"
twitter = "https://twitter.com/fuegowolf"