baseurl = "https://codewolf.fr/"

languageCode = "en-US"
title = "Codewolf"
summerization = "html_firstparagraph"
paginate = 5
theme = "bleak"

[permalinks]
  post = "/post/:year/:month/:day/:slug"
  project = "/project/:year/:month/:day/:slug"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  Subtitle = "Some blog about coding, cool stuff and machine learning."
  description = "Cool stuff and machine learning"
  cover = "/images/cover.png"
  logo = "/images/logo.png"
  disqus = "codewolf"

[author]
  FirstName = "Alexis"
  LastName = "Tacnet"
  Gender = "male"
  UserName = "fuego"
  Image = ""
  Bio = "I'm a man who loves to do code ! I'm very interested in Machine Learning and I would like to share my experiences about this exciting subject."
  Website = "http://codewolf.fr"
  Github = "https://github.com/fuegowolf"
  Page = "author"